// this is where your components are exported
export {default as Navbar} from './NavBar'
export {default as Home} from './Home'
export {default as AllItems} from './AllItems'
export {default as AllUsers} from './AllUsers'
export {default as Cart} from './Cart'
export {default as SingleUser} from './SingleUser'
export {default as SingleItem} from './SingleItem'
export {default as Login} from './Login'
export {default as NavBar} from './NavBar'
export {default as Register} from './Register'
